--------------------------------------------------------
--  파일이 생성됨 - 월요일-11월-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BID_COUPON
--------------------------------------------------------

  CREATE TABLE "BID"."BID_COUPON" 
   (	"COUPON_ID" NUMBER, 
	"COUPON_NAME" VARCHAR2(15 BYTE), 
	"DISCOUNT_PRICE" NUMBER, 
	"COUPON_STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BID"."BID_COUPON"."COUPON_ID" IS '쿠폰아이디';
   COMMENT ON COLUMN "BID"."BID_COUPON"."COUPON_NAME" IS '쿠폰명';
   COMMENT ON COLUMN "BID"."BID_COUPON"."DISCOUNT_PRICE" IS '할인금액';
   COMMENT ON COLUMN "BID"."BID_COUPON"."COUPON_STATUS" IS '쿠폰형태';
--------------------------------------------------------
--  DDL for Table BID_DEL
--------------------------------------------------------

  CREATE TABLE "BID"."BID_DEL" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(15 BYTE), 
	"USER_AGE" NUMBER, 
	"USER_GENDER" CHAR(1 BYTE), 
	"USER_EMAIL" VARCHAR2(100 BYTE), 
	"USER_ADDRESS" VARCHAR2(100 BYTE), 
	"USER_PHONE" VARCHAR2(15 BYTE), 
	"MEMBER_STATUS" CHAR(1 BYTE), 
	"MC_STATUS" CHAR(1 BYTE), 
	"ENROLL_DATE" DATE, 
	"ADMIN_STATUS" CHAR(1 BYTE), 
	"DEL_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BID_PRODUCT
--------------------------------------------------------

  CREATE TABLE "BID"."BID_PRODUCT" 
   (	"P_ID" VARCHAR2(30 BYTE), 
	"P_NAME" VARCHAR2(30 BYTE), 
	"P_SIZE" CHAR(1 BYTE), 
	"P_GENDER" CHAR(1 BYTE), 
	"P_PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BID"."BID_PRODUCT"."P_ID" IS '제품아이디';
   COMMENT ON COLUMN "BID"."BID_PRODUCT"."P_NAME" IS '제품명';
   COMMENT ON COLUMN "BID"."BID_PRODUCT"."P_SIZE" IS '사이즈';
   COMMENT ON COLUMN "BID"."BID_PRODUCT"."P_GENDER" IS '성별';
   COMMENT ON COLUMN "BID"."BID_PRODUCT"."P_PRICE" IS '가격';
--------------------------------------------------------
--  DDL for Table BID_USER
--------------------------------------------------------

  CREATE TABLE "BID"."BID_USER" 
   (	"USER_ID" VARCHAR2(30 BYTE), 
	"USER_PWD" VARCHAR2(30 BYTE), 
	"USER_NAME" VARCHAR2(15 BYTE), 
	"USER_AGE" NUMBER, 
	"USER_GENDER" CHAR(1 BYTE), 
	"USER_EMAIL" VARCHAR2(100 BYTE), 
	"USER_ADDRESS" VARCHAR2(100 BYTE), 
	"USER_PHONE" VARCHAR2(15 BYTE), 
	"MEMBER_STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"MC_STATUS" CHAR(1 BYTE) DEFAULT 'N', 
	"ENROLL_DATE" DATE DEFAULT SYSDATE, 
	"ADMIN_STATUS" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BID"."BID_USER"."USER_ID" IS '아이디';
   COMMENT ON COLUMN "BID"."BID_USER"."USER_PWD" IS '비밀번호';
   COMMENT ON COLUMN "BID"."BID_USER"."USER_NAME" IS '회원이름';
   COMMENT ON COLUMN "BID"."BID_USER"."USER_AGE" IS '회원나이';
   COMMENT ON COLUMN "BID"."BID_USER"."USER_GENDER" IS '회원성별';
   COMMENT ON COLUMN "BID"."BID_USER"."USER_EMAIL" IS '이메일';
   COMMENT ON COLUMN "BID"."BID_USER"."USER_ADDRESS" IS '주소';
   COMMENT ON COLUMN "BID"."BID_USER"."USER_PHONE" IS '전화번호';
   COMMENT ON COLUMN "BID"."BID_USER"."MEMBER_STATUS" IS '가입상태';
   COMMENT ON COLUMN "BID"."BID_USER"."MC_STATUS" IS '쿠폰여부';
   COMMENT ON COLUMN "BID"."BID_USER"."ENROLL_DATE" IS '가입일자';
   COMMENT ON COLUMN "BID"."BID_USER"."ADMIN_STATUS" IS '관리자여부';
REM INSERTING into BID.BID_COUPON
SET DEFINE OFF;
REM INSERTING into BID.BID_DEL
SET DEFINE OFF;
REM INSERTING into BID.BID_PRODUCT
SET DEFINE OFF;
REM INSERTING into BID.BID_USER
SET DEFINE OFF;
Insert into BID.BID_USER (USER_ID,USER_PWD,USER_NAME,USER_AGE,USER_GENDER,USER_EMAIL,USER_ADDRESS,USER_PHONE,MEMBER_STATUS,MC_STATUS,ENROLL_DATE,ADMIN_STATUS) values ('user01','pass01','김유신',20,'M','kim12@naver.com','서울시 강남구','010-2222-3333','Y','Y',to_date('21/11/13','RR/MM/DD'),'N');
Insert into BID.BID_USER (USER_ID,USER_PWD,USER_NAME,USER_AGE,USER_GENDER,USER_EMAIL,USER_ADDRESS,USER_PHONE,MEMBER_STATUS,MC_STATUS,ENROLL_DATE,ADMIN_STATUS) values ('user02','pass02','이순신',60,'M','lee2@naver.com','서울시 영등포구','010-5464-8845','N','Y',to_date('17/09/28','RR/MM/DD'),'N');
Insert into BID.BID_USER (USER_ID,USER_PWD,USER_NAME,USER_AGE,USER_GENDER,USER_EMAIL,USER_ADDRESS,USER_PHONE,MEMBER_STATUS,MC_STATUS,ENROLL_DATE,ADMIN_STATUS) values ('user03','pass03','유관순',17,'F','yo5@hanmail.net','수원시 팔달구','010-1234-5678','N','Y',to_date('19/10/14','RR/MM/DD'),'N');
Insert into BID.BID_USER (USER_ID,USER_PWD,USER_NAME,USER_AGE,USER_GENDER,USER_EMAIL,USER_ADDRESS,USER_PHONE,MEMBER_STATUS,MC_STATUS,ENROLL_DATE,ADMIN_STATUS) values ('user04','pass04','연개소문',57,'M','yeon@gmail.com','서울시 노원구','010-1134-2345','Y','Y',to_date('20/02/18','RR/MM/DD'),'N');
Insert into BID.BID_USER (USER_ID,USER_PWD,USER_NAME,USER_AGE,USER_GENDER,USER_EMAIL,USER_ADDRESS,USER_PHONE,MEMBER_STATUS,MC_STATUS,ENROLL_DATE,ADMIN_STATUS) values ('user05','pass05','신사임당',45,'F','shin@naver.com','서울시 구로구','010-2312-3333','N','Y',to_date('21/11/24','RR/MM/DD'),'N');
Insert into BID.BID_USER (USER_ID,USER_PWD,USER_NAME,USER_AGE,USER_GENDER,USER_EMAIL,USER_ADDRESS,USER_PHONE,MEMBER_STATUS,MC_STATUS,ENROLL_DATE,ADMIN_STATUS) values ('admin','admin','관리자',20,'M','admin@naver.com','서울시 강남구','010-1111-1111','Y','Y',to_date('17/01/01','RR/MM/DD'),'Y');
--------------------------------------------------------
--  DDL for Trigger TRG_DELETE_USER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BID"."TRG_DELETE_USER" 
    BEFORE DELETE ON BID_USER
    FOR EACH ROW
BEGIN 
    INSERT INTO BID_DEL
    VALUES(:OLD.USER_ID,:OLD.USER_PWD,:OLD.USER_NAME,:OLD.USER_AGE,:OLD.USER_GENDER,:OLD.USER_EMAIL,:OLD.USER_ADDRESS,:OLD.USER_PHONE,:OLD.MEMBER_STATUS, :OLD.ENROLL_DATE, :OLD.MC_STATUS,:OLD.ADMIN_STATUS, SYSDATE);
END;

/
ALTER TRIGGER "BID"."TRG_DELETE_USER" ENABLE;
--------------------------------------------------------
--  Constraints for Table BID_PRODUCT
--------------------------------------------------------

  ALTER TABLE "BID"."BID_PRODUCT" MODIFY ("P_GENDER" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_PRODUCT" MODIFY ("P_SIZE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_PRODUCT" MODIFY ("P_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_PRODUCT" ADD CHECK (P_GENDER IN ('M', 'F')) ENABLE;
  ALTER TABLE "BID"."BID_PRODUCT" ADD CHECK (P_SIZE IN ('S','M','L')) ENABLE;
  ALTER TABLE "BID"."BID_PRODUCT" MODIFY ("P_NAME" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_PRODUCT" ADD PRIMARY KEY ("P_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BID_COUPON
--------------------------------------------------------

  ALTER TABLE "BID"."BID_COUPON" MODIFY ("COUPON_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_COUPON" MODIFY ("DISCOUNT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_COUPON" MODIFY ("COUPON_NAME" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_COUPON" MODIFY ("COUPON_ID" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_COUPON" ADD CHECK (COUPON_STATUS IN ('Y', 'N')) ENABLE;
  ALTER TABLE "BID"."BID_COUPON" ADD UNIQUE ("COUPON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BID_USER
--------------------------------------------------------

  ALTER TABLE "BID"."BID_USER" ADD CHECK (ADMIN_STATUS IN ('Y','N')) ENABLE;
  ALTER TABLE "BID"."BID_USER" ADD CHECK (MC_STATUS IN ('Y','N')) ENABLE;
  ALTER TABLE "BID"."BID_USER" ADD CHECK (MEMBER_STATUS IN ('Y','N')) ENABLE;
  ALTER TABLE "BID"."BID_USER" ADD CHECK (USER_GENDER IN ('M','F')) ENABLE;
  ALTER TABLE "BID"."BID_USER" MODIFY ("ADMIN_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("ENROLL_DATE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("MC_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("MEMBER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("USER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("USER_GENDER" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("USER_AGE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BID_DEL
--------------------------------------------------------

  ALTER TABLE "BID"."BID_DEL" MODIFY ("DEL_DATE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("ADMIN_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("ENROLL_DATE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("MC_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("MEMBER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("USER_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("USER_GENDER" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("USER_AGE" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "BID"."BID_DEL" MODIFY ("USER_ID" NOT NULL ENABLE);
